model:
    name: 'SelfSupModel'
    loss:
        eval_self_sup_loss: True
datasets:
    test:
        back_context: 1
        forward_context: 1
        stereo_context: True
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['groundtruth']
save:
    folder: '/save/eval'
    depth:
        rgb: True
        viz: True
        npz: False
        png: False
