checkpoint:
    filepath: '/save/checkpoints'
    save_top_k: 10
    monitor: 'abs_rel_pp'
    mode: 'min'
tensorboard:
    log_dir: '/save/logs'
arch:
    max_epochs: 50
    validate_first: True
model:
    name: 'SemiSupCompletionModel'
    checkpoint_path: '/save/models/sparse+self_m90_resnet_kitti_lr.ckpt'
    loss:
        self_sup_signal: 'M'
        supervised_method: 'sparse-silog'
        supervised_num_scales: 1
        supervised_loss_weight: 0.1
        eval_self_sup_loss: True
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.0001
            weight_decay: 0.01
        pose:
            lr: 0.0001
            weight_decay: 0.01
    scheduler:
        name: 'StepLR'
        step_size: 10
        gamma: 0.5
    depth_net:
        name: 'DepthResNetSAN'
        version: '18pt'
        grad_image_encoder: False
        scale_output: False
        dropout: 0.5
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 16
        stereo_context: True
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_zhou_files.txt']
        input_depth_type: ['velodyne']
        depth_type: ['velodyne']
    validation:
        back_context: 1
        forward_context: 1
        stereo_context: True
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt',
                'data_splits/eigen_test_files.txt']
        input_depth_type: ['velodyne','','velodyne','']
        depth_type: ['velodyne','velodyne',
                     'velodyne','velodyne']
    test:
        back_context: 1
        forward_context: 1
        stereo_context: True
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt',
                'data_splits/eigen_test_files.txt']
        input_depth_type: ['velodyne','']
        depth_type: ['velodyne','velodyne']
