checkpoint:
    filepath: '/save/checkpoints'
    save_top_k: 10
    monitor: 'abs_rel_pp'
    mode: 'min'
tensorboard:
    log_dir: '/save/logs'
arch:
    max_epochs: 10
    validate_first: True
model:
    name: 'SemiSupModel'
    loss:
        self_sup_signal: 'M'
        supervised_method: 'sparse-silog'
        supervised_num_scales: 1
        supervised_loss_weight: 0.1
        eval_self_sup_loss: False
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.0001
            weight_decay: 0.01
        pose:
            lr: 0.0001
            weight_decay: 0.01
    scheduler:
        name: 'StepLR'
        step_size: 10
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
        scale_output: False
        dropout: 0.5
        adjust_depth: True
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        crop_train_borders: (0.5, 640, 0, 1280)
        crop_eval_borders: (0.5, 640, 0, 1280)
        image_shape: (256, 512)
    train:
        batch_size: 16
        dataset: ['Scania']
        path: ['/data/datasets/depth_completion']
        split: ['train.txt']
        depth_type: ['depth']
    validation:
        back_context: 1
        forward_context: 1
        dataset: ['Scania']
        path: ['/data/datasets/depth_completion']
        split: ['val.txt','test.txt']
        depth_type: ['depth','depth']
    test:
        back_context: 1
        forward_context: 1
        dataset: ['Scania']
        path: ['/data/datasets/depth_completion']
        split: ['test.txt']
        depth_type: ['depth']
