checkpoint:
    filepath: '/save/checkpoints'
    save_top_k: 10
    monitor: 'abs_rel_pp'
    mode: 'min'
tensorboard:
    log_dir: '/save/logs'
arch:
    max_epochs: 10
    validate_first: True
model:
    name: 'SemiSupModel'
    loss:
        supervised_method: 'sparse-silog'
        supervised_num_scales: 1
        supervised_loss_weight: 1.0
        eval_self_sup_loss: True
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.0001
            weight_decay: 0.01
    scheduler:
        name: 'StepLR'
        step_size: 10
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'
        dropout: 0.5
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_zhou_files.txt']
        depth_type: ['groundtruth']
    validation:
        back_context: 1
        forward_context: 1
        stereo_context: True
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt']
        depth_type: ['groundtruth','groundtruth']
    test:
        back_context: 1
        forward_context: 1
        stereo_context: True
        dataset: ['KITTI']
        path: ['/data/datasets/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['groundtruth']
